/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedMediaRouteImport } from './routes/_authed/media'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedPagesIndexRouteImport } from './routes/_authed/pages/index'
import { Route as AuthedPagesPageIdRouteImport } from './routes/_authed/pages/$pageId'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts/index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts/$postId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMediaRoute = AuthedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPagesIndexRoute = AuthedPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPagesPageIdRoute = AuthedPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/media': typeof AuthedMediaRoute
  '/users': typeof AuthedUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/pages/$pageId': typeof AuthedPagesPageIdRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pages/': typeof AuthedPagesIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/media': typeof AuthedMediaRoute
  '/users': typeof AuthedUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/pages/$pageId': typeof AuthedPagesPageIdRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pages': typeof AuthedPagesIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/_authed/media': typeof AuthedMediaRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/pages/$pageId': typeof AuthedPagesPageIdRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/pages/': typeof AuthedPagesIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/media'
    | '/users'
    | '/api/health'
    | '/pages/$pageId'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/pages/'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/login'
    | '/media'
    | '/users'
    | '/api/health'
    | '/'
    | '/pages/$pageId'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/pages'
    | '/posts'
  id:
    | '__root__'
    | '/_authed'
    | '/accept-invite'
    | '/login'
    | '/_authed/media'
    | '/_authed/users'
    | '/api/health'
    | '/_authed/'
    | '/_authed/pages/$pageId'
    | '/_authed/posts/$postId'
    | '/api/auth/$'
    | '/_authed/pages/'
    | '/_authed/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/media': {
      id: '/_authed/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthedMediaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/pages/': {
      id: '/_authed/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthedPagesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pages/$pageId': {
      id: '/_authed/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof AuthedPagesPageIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedMediaRoute: typeof AuthedMediaRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPagesPageIdRoute: typeof AuthedPagesPageIdRoute
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPagesIndexRoute: typeof AuthedPagesIndexRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedMediaRoute: AuthedMediaRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPagesPageIdRoute: AuthedPagesPageIdRoute,
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPagesIndexRoute: AuthedPagesIndexRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
