/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedCompteRouteImport } from './routes/_authed/compte'
import { Route as AuthedLeadsRouteImport } from './routes/_authed/leads'
import { Route as AuthedMediaRouteImport } from './routes/_authed/media'
import { Route as AuthedRedirectsRouteImport } from './routes/_authed/redirects'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedStatistiquesRouteImport } from './routes/_authed/statistiques'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthedPagesIndexRouteImport } from './routes/_authed/pages/index'
import { Route as AuthedPagesPageIdRouteImport } from './routes/_authed/pages/$pageId'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts/index'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts/$postId'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedSettingsDomaineRouteImport } from './routes/_authed/settings/domaine'
import { Route as AuthedSettingsEmailsRouteImport } from './routes/_authed/settings/emails'
import { Route as AuthedSettingsIaRouteImport } from './routes/_authed/settings/ia'
import { Route as AuthedSettingsIdentiteRouteImport } from './routes/_authed/settings/identite'
import { Route as AuthedSettingsMesureRouteImport } from './routes/_authed/settings/mesure'
import { Route as AuthedSettingsReferencementRouteImport } from './routes/_authed/settings/referencement'
import { Route as AuthedSettingsReseauxRouteImport } from './routes/_authed/settings/reseaux'
import { Route as AuthedSettingsWebhookRouteImport } from './routes/_authed/settings/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCompteRoute = AuthedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLeadsRoute = AuthedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMediaRoute = AuthedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRedirectsRoute = AuthedRedirectsRouteImport.update({
  id: '/redirects',
  path: '/redirects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStatistiquesRoute = AuthedStatistiquesRouteImport.update({
  id: '/statistiques',
  path: '/statistiques',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPagesIndexRoute = AuthedPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPagesPageIdRoute = AuthedPagesPageIdRouteImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsDomaineRoute = AuthedSettingsDomaineRouteImport.update({
  id: '/domaine',
  path: '/domaine',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsEmailsRoute = AuthedSettingsEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsIaRoute = AuthedSettingsIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsIdentiteRoute = AuthedSettingsIdentiteRouteImport.update({
  id: '/identite',
  path: '/identite',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsMesureRoute = AuthedSettingsMesureRouteImport.update({
  id: '/mesure',
  path: '/mesure',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsReferencementRoute =
  AuthedSettingsReferencementRouteImport.update({
    id: '/referencement',
    path: '/referencement',
    getParentRoute: () => AuthedSettingsRoute,
  } as any)
const AuthedSettingsReseauxRoute = AuthedSettingsReseauxRouteImport.update({
  id: '/reseaux',
  path: '/reseaux',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const AuthedSettingsWebhookRoute = AuthedSettingsWebhookRouteImport.update({
  id: '/webhook',
  path: '/webhook',
  getParentRoute: () => AuthedSettingsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/compte': typeof AuthedCompteRoute
  '/leads': typeof AuthedLeadsRoute
  '/media': typeof AuthedMediaRoute
  '/redirects': typeof AuthedRedirectsRoute
  '/settings': typeof AuthedSettingsRouteWithChildren
  '/statistiques': typeof AuthedStatistiquesRoute
  '/users': typeof AuthedUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/pages/$pageId': typeof AuthedPagesPageIdRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/settings/domaine': typeof AuthedSettingsDomaineRoute
  '/settings/emails': typeof AuthedSettingsEmailsRoute
  '/settings/ia': typeof AuthedSettingsIaRoute
  '/settings/identite': typeof AuthedSettingsIdentiteRoute
  '/settings/mesure': typeof AuthedSettingsMesureRoute
  '/settings/referencement': typeof AuthedSettingsReferencementRoute
  '/settings/reseaux': typeof AuthedSettingsReseauxRoute
  '/settings/webhook': typeof AuthedSettingsWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pages/': typeof AuthedPagesIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/compte': typeof AuthedCompteRoute
  '/leads': typeof AuthedLeadsRoute
  '/media': typeof AuthedMediaRoute
  '/redirects': typeof AuthedRedirectsRoute
  '/statistiques': typeof AuthedStatistiquesRoute
  '/users': typeof AuthedUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AuthedIndexRoute
  '/pages/$pageId': typeof AuthedPagesPageIdRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/settings/domaine': typeof AuthedSettingsDomaineRoute
  '/settings/emails': typeof AuthedSettingsEmailsRoute
  '/settings/ia': typeof AuthedSettingsIaRoute
  '/settings/identite': typeof AuthedSettingsIdentiteRoute
  '/settings/mesure': typeof AuthedSettingsMesureRoute
  '/settings/referencement': typeof AuthedSettingsReferencementRoute
  '/settings/reseaux': typeof AuthedSettingsReseauxRoute
  '/settings/webhook': typeof AuthedSettingsWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pages': typeof AuthedPagesIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/compte': typeof AuthedCompteRoute
  '/_authed/leads': typeof AuthedLeadsRoute
  '/_authed/media': typeof AuthedMediaRoute
  '/_authed/redirects': typeof AuthedRedirectsRoute
  '/_authed/settings': typeof AuthedSettingsRouteWithChildren
  '/_authed/statistiques': typeof AuthedStatistiquesRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/api/health': typeof ApiHealthRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/pages/$pageId': typeof AuthedPagesPageIdRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/settings/domaine': typeof AuthedSettingsDomaineRoute
  '/_authed/settings/emails': typeof AuthedSettingsEmailsRoute
  '/_authed/settings/ia': typeof AuthedSettingsIaRoute
  '/_authed/settings/identite': typeof AuthedSettingsIdentiteRoute
  '/_authed/settings/mesure': typeof AuthedSettingsMesureRoute
  '/_authed/settings/referencement': typeof AuthedSettingsReferencementRoute
  '/_authed/settings/reseaux': typeof AuthedSettingsReseauxRoute
  '/_authed/settings/webhook': typeof AuthedSettingsWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/pages/': typeof AuthedPagesIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/compte'
    | '/leads'
    | '/media'
    | '/redirects'
    | '/settings'
    | '/statistiques'
    | '/users'
    | '/api/health'
    | '/pages/$pageId'
    | '/posts/$postId'
    | '/settings/domaine'
    | '/settings/emails'
    | '/settings/ia'
    | '/settings/identite'
    | '/settings/mesure'
    | '/settings/referencement'
    | '/settings/reseaux'
    | '/settings/webhook'
    | '/api/auth/$'
    | '/pages/'
    | '/posts/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/compte'
    | '/leads'
    | '/media'
    | '/redirects'
    | '/statistiques'
    | '/users'
    | '/api/health'
    | '/'
    | '/pages/$pageId'
    | '/posts/$postId'
    | '/settings/domaine'
    | '/settings/emails'
    | '/settings/ia'
    | '/settings/identite'
    | '/settings/mesure'
    | '/settings/referencement'
    | '/settings/reseaux'
    | '/settings/webhook'
    | '/api/auth/$'
    | '/pages'
    | '/posts'
    | '/settings'
  id:
    | '__root__'
    | '/_authed'
    | '/accept-invite'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/compte'
    | '/_authed/leads'
    | '/_authed/media'
    | '/_authed/redirects'
    | '/_authed/settings'
    | '/_authed/statistiques'
    | '/_authed/users'
    | '/api/health'
    | '/_authed/'
    | '/_authed/pages/$pageId'
    | '/_authed/posts/$postId'
    | '/_authed/settings/domaine'
    | '/_authed/settings/emails'
    | '/_authed/settings/ia'
    | '/_authed/settings/identite'
    | '/_authed/settings/mesure'
    | '/_authed/settings/referencement'
    | '/_authed/settings/reseaux'
    | '/_authed/settings/webhook'
    | '/api/auth/$'
    | '/_authed/pages/'
    | '/_authed/posts/'
    | '/_authed/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/compte': {
      id: '/_authed/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthedCompteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leads': {
      id: '/_authed/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthedLeadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/media': {
      id: '/_authed/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthedMediaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/redirects': {
      id: '/_authed/redirects'
      path: '/redirects'
      fullPath: '/redirects'
      preLoaderRoute: typeof AuthedRedirectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/statistiques': {
      id: '/_authed/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthedStatistiquesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/pages/': {
      id: '/_authed/pages/'
      path: '/pages'
      fullPath: '/pages/'
      preLoaderRoute: typeof AuthedPagesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pages/$pageId': {
      id: '/_authed/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof AuthedPagesPageIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/domaine': {
      id: '/_authed/settings/domaine'
      path: '/domaine'
      fullPath: '/settings/domaine'
      preLoaderRoute: typeof AuthedSettingsDomaineRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/emails': {
      id: '/_authed/settings/emails'
      path: '/emails'
      fullPath: '/settings/emails'
      preLoaderRoute: typeof AuthedSettingsEmailsRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/ia': {
      id: '/_authed/settings/ia'
      path: '/ia'
      fullPath: '/settings/ia'
      preLoaderRoute: typeof AuthedSettingsIaRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/identite': {
      id: '/_authed/settings/identite'
      path: '/identite'
      fullPath: '/settings/identite'
      preLoaderRoute: typeof AuthedSettingsIdentiteRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/mesure': {
      id: '/_authed/settings/mesure'
      path: '/mesure'
      fullPath: '/settings/mesure'
      preLoaderRoute: typeof AuthedSettingsMesureRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/referencement': {
      id: '/_authed/settings/referencement'
      path: '/referencement'
      fullPath: '/settings/referencement'
      preLoaderRoute: typeof AuthedSettingsReferencementRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/reseaux': {
      id: '/_authed/settings/reseaux'
      path: '/reseaux'
      fullPath: '/settings/reseaux'
      preLoaderRoute: typeof AuthedSettingsReseauxRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/_authed/settings/webhook': {
      id: '/_authed/settings/webhook'
      path: '/webhook'
      fullPath: '/settings/webhook'
      preLoaderRoute: typeof AuthedSettingsWebhookRouteImport
      parentRoute: typeof AuthedSettingsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedSettingsRouteChildren {
  AuthedSettingsDomaineRoute: typeof AuthedSettingsDomaineRoute
  AuthedSettingsEmailsRoute: typeof AuthedSettingsEmailsRoute
  AuthedSettingsIaRoute: typeof AuthedSettingsIaRoute
  AuthedSettingsIdentiteRoute: typeof AuthedSettingsIdentiteRoute
  AuthedSettingsMesureRoute: typeof AuthedSettingsMesureRoute
  AuthedSettingsReferencementRoute: typeof AuthedSettingsReferencementRoute
  AuthedSettingsReseauxRoute: typeof AuthedSettingsReseauxRoute
  AuthedSettingsWebhookRoute: typeof AuthedSettingsWebhookRoute
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
}

const AuthedSettingsRouteChildren: AuthedSettingsRouteChildren = {
  AuthedSettingsDomaineRoute: AuthedSettingsDomaineRoute,
  AuthedSettingsEmailsRoute: AuthedSettingsEmailsRoute,
  AuthedSettingsIaRoute: AuthedSettingsIaRoute,
  AuthedSettingsIdentiteRoute: AuthedSettingsIdentiteRoute,
  AuthedSettingsMesureRoute: AuthedSettingsMesureRoute,
  AuthedSettingsReferencementRoute: AuthedSettingsReferencementRoute,
  AuthedSettingsReseauxRoute: AuthedSettingsReseauxRoute,
  AuthedSettingsWebhookRoute: AuthedSettingsWebhookRoute,
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
}

const AuthedSettingsRouteWithChildren = AuthedSettingsRoute._addFileChildren(
  AuthedSettingsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCompteRoute: typeof AuthedCompteRoute
  AuthedLeadsRoute: typeof AuthedLeadsRoute
  AuthedMediaRoute: typeof AuthedMediaRoute
  AuthedRedirectsRoute: typeof AuthedRedirectsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRouteWithChildren
  AuthedStatistiquesRoute: typeof AuthedStatistiquesRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedPagesPageIdRoute: typeof AuthedPagesPageIdRoute
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPagesIndexRoute: typeof AuthedPagesIndexRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCompteRoute: AuthedCompteRoute,
  AuthedLeadsRoute: AuthedLeadsRoute,
  AuthedMediaRoute: AuthedMediaRoute,
  AuthedRedirectsRoute: AuthedRedirectsRoute,
  AuthedSettingsRoute: AuthedSettingsRouteWithChildren,
  AuthedStatistiquesRoute: AuthedStatistiquesRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedPagesPageIdRoute: AuthedPagesPageIdRoute,
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPagesIndexRoute: AuthedPagesIndexRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
