import { describe, expect, test } from "vitest"
import source from "./agent.tsx?raw"

describe("settings/agent — chrome des réglages", () => {
  test("porte la barre d'enregistrement, pas seulement l'en-tête", () => {
    expect(source).toContain("SettingsFormShell")
    expect(source).toContain("useAutoSave")
    expect(source).not.toContain("SettingsPageShell")
  })

  test("porte AiPage et les trois sections, plus de lien vers /settings/ia", () => {
    expect(source).toContain("AiPage")
    expect(source).toContain("Identité de l'agent")
    expect(source).toContain("Applications")
    expect(source).toContain("Base de savoir")
    expect(source).toContain("AgentConnectorsRow")
    expect(source).toContain("AgentKnowledgeFiles")
    expect(source).toContain("AgentPreviewBubble")
    expect(source).toContain("api.settings.updateAgent")
    expect(source).toContain("agentChatColor")
    expect(source).toContain("agentTeaser")
    expect(source).toContain("DEFAULT_AGENT_CHAT_COLOR")
    expect(source).toContain("color={agentChatColor}")
    expect(source).toContain("teaser={agentTeaser}")
    expect(source).toContain("agentName={agentDisplayName}")
    expect(source).toContain("api.settings.ensureDefaultAgentInstructions")
    expect(source).toContain("DEFAULT_AGENT_INSTRUCTIONS")
    expect(source).toContain("hasAuthoredAgentInstructions")
    expect(source).toMatch(/ensureInstructions\(\{\}\)[\s\S]*setAgentInstructions/)
    expect(source).toContain("onSaveModel")
    expect(source).toContain("onSaveImageModel")
    expect(source).toContain("OcrModelSelect")
    expect(source).toContain("openRouterOcrModel")
    expect(source).not.toContain('to="/settings/ia"')
    expect(source).not.toContain("Configurer la clé sur l'écran IA")
    expect(source).not.toContain("AgentCalendarCard")
    expect(source).not.toContain("AgentMcpCard")
    expect(source).not.toContain("GOOGLE_CALENDAR_CLIENT_SECRET")
    expect(source).not.toMatch(/SettingsGroup[\s\S]*title="Applications"/)
    expect(source).not.toMatch(/SettingsGroup[\s\S]*title="Base de savoir"/)
  })

  test("l'ordre est identité (savoir puis applications), modèle", () => {
    const identite = source.indexOf("Identité de l'agent")
    const savoir = source.indexOf("Base de savoir")
    const apps = source.indexOf("Applications")
    const ai = source.indexOf("<AiPage")
    const ocr = source.indexOf("<OcrModelSelect")
    const bulle = source.indexOf("<AgentPreviewBubble")
    expect(identite).toBeGreaterThan(-1)
    expect(savoir).toBeGreaterThan(identite)
    expect(apps).toBeGreaterThan(savoir)
    expect(ai).toBeGreaterThan(apps)
    expect(ocr).toBeGreaterThan(ai)
    expect(bulle).toBeGreaterThan(ocr)
  })

  test("importe les bornes depuis content, pas depuis settings", () => {
    expect(source).not.toContain("@astrotan/backend/convex/settings")
  })

  test("Tester ouvre l'aperçu, fermé par défaut, sans pastille", () => {
    expect(source).toContain("useState(false)")
    expect(source).toContain("setPreviewOpen(true)")
    expect(source).toMatch(/>\s*Tester\s*</)
    expect(source).toContain('aria-label="Tester"')
    expect(source).toContain("Zap")
    expect(source).not.toContain('size="icon"')
    expect(source).toContain("open={previewOpen}")
    expect(source).toContain("onOpenChange={setPreviewOpen}")
    expect(source).not.toContain("Aperçu")
    expect(source).not.toContain("aucun lead")
    const identite = source.indexOf("Identité de l'agent")
    const tester = source.indexOf("Tester", identite)
    const fields = source.indexOf("<AgentIdentityFields")
    expect(tester).toBeGreaterThan(identite)
    expect(tester).toBeLessThan(fields)
  })
})
