// GENERATED by scripts/generate-served-paths.mjs — do not edit.
//
// The paths this site's own route files answer on. See the generator for
// why this is generated rather than written by hand, and why a redirect
// has to check it.

/** Paths a route file serves exactly. */
export const SERVED_PATHS: readonly string[] = [
  "/",
  "/404",
  "/blog",
  "/confidentialite",
  "/contact",
  "/cookies",
  "/fonctionnalites",
  "/mentions-legales",
  "/paiement-annule",
  "/paiement-ok",
  "/tarifs"
]

/** Prefixes a dynamic route serves everything under. */
export const SERVED_PREFIXES: readonly string[] = [
  "/blog"
]
